### ISSUE TITLE
關於MPU9250的加速度計問題

### ISSUE THREAD

**Issue by smallchicken0204** [KitSprout/QCopterFlightControl#11]
您好，我是台北大學資工系的研究生，目前做的研究是將IMU放置在手腕上追蹤手部軌跡，而遇到的問題是，當加速度計從運動狀態急停的時候，似乎會出現與運動方向相反的加速度，導致軌跡會出現到達目標位置時(15CM處)，瞬間往後倒退3~5CM(12CM處)，想詢問您有沒有遇過相關的問題?

**Comment by brennenhuang** [comment]
請問是real time還是事後分析呢？

smallchicken0204 <notifications@github.com>於 2019年8月10日 週六，下午5:02寫道：

**Comment by smallchicken0204** [comment]
real time的，我是設計成每收集20筆加速度資料，進行一次計算。

**Comment by brennenhuang** [comment]
如果軌跡在動時有明確的起始，那可以用零速補償，如果是一直持續的動態一定會有積分飄移，然後記得用濾波器濾雜訊

smallchicken0204 <notifications@github.com>於 2019年8月10日 週六，下午8:35寫道：

**Comment by smallchicken0204** [comment]
瞭解，目前有使用簡易的零速補償，我先嘗試去改良一下零速補償這塊看看，感謝您的回答。

**Comment by brennenhuang** [comment]
加油keep going

smallchicken0204 <notifications@github.com>於 2019年8月10日 週六，下午10:12寫道：

**Comment by smallchicken0204** [comment]
您好，我想再跟您請教一下MPU9250的問題，目前我打算驗證位移距離，所以做了一個軌道平台(如附圖一)，這平台是讓IMU單純沿著x軸來回滑動且軌道算是光滑不會震動，但是發現row data裡面的Z軸加速度會出現過大的振幅，所以我做了一個測試是在軌道滑動數次，再用手持IMU在空中移動數次，得到row data(如附圖二)Y軸是加速度(單位:g)X軸為樣本數，左邊紅色框框是在軌道上滑動得到的數值，右邊紅色框框則是空中滑動的，因為差異其實蠻大的，我不太能確定是否全為摩擦震動導致，想詢問您有沒有遇過相關的情況?
![DSC_0341](https://user-images.githubusercontent.com/11404052/66104720-18a4b200-e5ec-11e9-83c2-ce8f8f9f3a5c.JPG)
![Z軸加速度](https://user-images.githubusercontent.com/11404052/66104721-18a4b200-e5ec-11e9-8446-0e6fced4b3b6.png)
