### ISSUE TITLE
MPU9250加速度Z軸的問題

### ISSUE THREAD

**Issue by smallchicken0204** [KitSprout/QCopterFlightControl#12]
您好，我想跟您請教一下MPU9250的問題，目前我打算驗證位移距離，所以做了一個軌道平台(如附圖一)，這平台是讓IMU單純沿著x軸來回滑動，而且軌道算是光滑不會震動，但是發現row data裡面的Z軸加速度會出現過大的振幅，所以我做了一個測試是在軌道滑動數次，再用手持IMU在空中移動數次，得到row data(如附圖二)Y軸是加速度(單位:g)X軸為樣本數，左邊紅色框框是在軌道上滑動得到的數值，右邊紅色框框則是空中滑動的，因為差異其實蠻大的，我不太能確定是否全為摩擦震動導致，想詢問您有沒有遇過相關的情況?
![DSC_0341](https://user-images.githubusercontent.com/11404052/66380065-3eb1c400-e9e9-11e9-8541-56e642e2b151.JPG)
![Z軸加速度](https://user-images.githubusercontent.com/11404052/66380096-4cffe000-e9e9-11e9-8b74-e1bf11edaa20.png)

**Comment by brennenhuang** [comment]
看起來Z軸呈現的確實怪,你要不要把他的Z軸跟X軸或Y軸對調,重複做一樣的實驗,看會不會重現此問題,讓x或y軸朝上,祝你一切順利

**Comment by smallchicken0204** [comment]
對調Y軸跟Z軸後，意外發現問題所在了，謝謝您的建議~

**Comment by brennenhuang** [comment]
讚喔，之後有問題也可以用賴問，研究的問題通常都不太能等，我的賴：jimpaul15，如果有要加可以說一聲，我剛好也在台北工作，加油嘍，對了也可以用email問，只是通常可能不會天天看email

smallchicken0204 <notifications@github.com>於 2019年10月10日 週四，下午3:42寫道：

**Comment by smallchicken0204** [comment]
好的，那我加一下您的Line。
